version: '3.8'

services:
  web:
    container_name: cnr_orga_web
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    restart: on-failure
  db:
    container_name: cnr_orga_db
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chummy
      POSTGRES_DB: cnr_orga
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: on-failure

volumes:
  postgres_data:
