# Generated by Django 4.1.7 on 2023-04-13 14:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["start", "end"],
                "verbose_name": "Concertation",
                "verbose_name_plural": "Concertations",
            },
        ),
    ]
