# Generated by Django 4.1.7 on 2023-05-05 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0003_booking"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contribution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[("proposal", "Proposition"), ("idea", "Idée"), ("project", "Projet")],
                        default="proposal",
                        max_length=8,
                        verbose_name="Nature",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Titre")),
                ("description", models.TextField(verbose_name="Description")),
                ("public", models.BooleanField(verbose_name="Publique")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="contribute", to="event.event"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContributionStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("change_on", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("uns", "Non retenue"), ("stu", "En cours d'étude"), ("sel", "Retenue")],
                        default="stu",
                        max_length=5,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "contribution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contribution_evolution",
                        to="event.contribution",
                    ),
                ),
            ],
        ),
    ]
