# Generated by Django 4.1.7 on 2023-05-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0004_contribution_contributionstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="theme",
            field=models.CharField(
                choices=[("sante", "Santé"), ("biodiv", "Biodiversité"), ("num", "Numérique")],
                max_length=6,
                verbose_name="Thématique",
            ),
        ),
    ]
