# Generated by Django 4.1.9 on 2023-05-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0005_alter_event_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="place_name",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Lieu"),
        ),
    ]
