# Generated by Django 4.1.9 on 2023-05-22 09:24

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("event", "0006_event_place_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="Ajoutez des étiquettes (tags) séparés par des virgules",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Étiquettes",
            ),
        ),
    ]
