# Generated by Django 4.1.9 on 2023-05-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0008_alter_booking_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributionstatus",
            name="status",
            field=models.CharField(
                choices=[("stu", "En cours d'étude"), ("uns", "Non retenue"), ("sel", "Retenue")],
                default="stu",
                max_length=5,
                verbose_name="Statut",
            ),
        ),
    ]
