# Generated by Django 4.1.9 on 2023-05-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0009_alter_contributionstatus_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="theme",
            field=models.CharField(
                choices=[
                    ("assist", "Assises du travail"),
                    ("vieill", "Bien vieillir"),
                    ("biodiv", "Climat et Biodiversité"),
                    ("ecole", "École"),
                    ("fratra", "France Travail"),
                    ("jeunes", "Jeunesse"),
                    ("logeme", "Logement"),
                    ("prosoc", "Modèle productif et social"),
                    ("num", "Numérique"),
                    ("enfanc", "Petite enfance"),
                    ("sante", "Santé"),
                ],
                max_length=6,
                verbose_name="Thématique",
            ),
        ),
    ]
