# Generated by Django 4.1.9 on 2023-06-06 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0010_alter_event_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="synthesis",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="synthesis",
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
                verbose_name="Synthèse",
            ),
        ),
    ]
