# Generated by Django 4.1.9 on 2023-06-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0012_fill_first_organizer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="theme",
            field=models.CharField(
                choices=[
                    ("assist", "Assises du travail"),
                    ("vieill", "Bien vieillir"),
                    ("biodiv", "Climat et Biodiversité"),
                    ("ecole", "École"),
                    ("fratra", "France Travail"),
                    ("jeunes", "Jeunesse"),
                    ("logeme", "Logement"),
                    ("num", "Numérique"),
                    ("sante", "Santé"),
                ],
                max_length=6,
                verbose_name="Thématique",
            ),
        ),
    ]
